version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: